server:
  port: ${PORT:0}

spring:
  application:
    name: hr-user
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: root
  jpa:
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console