server:
  port: 8765

spring:
  application:
    name: hr-api-gateway-zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

zuul:
  routes:
    worker:
      serviceId: hr-worker
      path: /hr-worker/**
    payroll:
      serviceId: hr-payroll
      path: /hr-payroll/**